"""Maintained source data for the ICAM / Zero Trust gap register.

This module is the single source of truth for every value that appears in
ICAM-ZT-Gap-Register.xlsx. Edit this file, then re-run icam_gap_register.py.
Do not hand-edit the workbook.

Evidence locations are ``path:line`` references into this repository at the
commit recorded in METHOD["Baseline commit"]. Where no authoritative public
requirement exists (DAF-specific ICAM direction), the requirement source is
recorded as "Needs Government input" and the row is expected to be replaced
by Government-furnished direction.
"""

BASELINE_COMMIT = "c0662050"

PILLARS = [
    "User",
    "Device",
    "Applications & Workloads",
    "Data",
    "Network & Environment",
    "Automation & Orchestration",
    "Visibility & Analytics",
]

RISK_LEVELS = ("H", "M", "L")
EFFORT_LEVELS = ("S", "M", "L")
PHASES = ("Phase 0", "Phase 1", "Phase 2", "Phase 3", "Phase 4")

GAP_COLUMNS = [
    "Gap ID",
    "Affected system/service (component + file:line)",
    "ZT pillar",
    "Requirement source (document + control/activity ID)",
    "Current state (evidence)",
    "Gap",
    "Risk (H/M/L with rationale)",
    "Proposed corrective action",
    "Responsible Government decision authority (role — e.g., AO, ISSM, Program Office, Enterprise ICAM PMO)",
    "Estimated implementation dependency (what must exist first)",
    "Effort (S/M/L)",
    "Recommended sequence (phase)",
]

# Requirement sources. Every URL below was opened from this assessment
# environment and confirmed to return the cited document. Sources without a
# URL could not be opened from the assessment environment and are cited by
# title only; the Government should furnish the authoritative copy.
SOURCES = [
    {
        "id": "DoD-ZTS",
        "title": "DoD Zero Trust Strategy, Version 1.0 (October 21, 2022; cleared for open publication November 7, 2022)",
        "url": "https://dodcio.defense.gov/Portals/0/Documents/Library/DoD-ZTStrategy.pdf",
        "verified": "Opened in browser; 37-page PDF titled 'DoD Zero Trust Strategy', dated October 21, 2022.",
    },
    {
        "id": "DoD-ZTER",
        "title": "DoD Zero Trust Capability Execution Roadmap (COA 1), 15 November 2022",
        "url": "https://dodcio.defense.gov/Portals/0/Documents/Library/DoD-ZTExecutionRoadmap.pdf",
        "verified": "Opened in browser; 58-page PDF. Capability and activity names cited from the roadmap slides.",
    },
    {
        "id": "DoD-ICAM-RD",
        "title": "DoD Enterprise Identity, Credential, and Access Management (ICAM) Reference Design, Version 1.0, June 2020",
        "url": "https://dodcio.defense.gov/Portals/0/Documents/Cyber/DoD_Enterprise_ICAM_Reference_Design.pdf",
        "verified": "Opened in browser; 123-page PDF, cover states Version 1.0, June 2020, prepared by DoD CIO.",
    },
    {
        "id": "DoDI-8520.03",
        "title": "DoDI 8520.03, Identity Authentication for Information Systems, May 19, 2023",
        "url": "https://www.esd.whs.mil/Portals/54/Documents/DD/issuances/dodi/852003p.pdf",
        "verified": "Downloaded and text-extracted; sections 3.2, 3.3, 3.4, 3.6 cited.",
    },
    {
        "id": "NIST-800-53r5",
        "title": "NIST SP 800-53 Rev. 5 (including Update 1), Security and Privacy Controls for Information Systems and Organizations",
        "url": "https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final",
        "verified": "Opened; CSRC publication page.",
    },
    {
        "id": "NIST-800-63-4",
        "title": "NIST SP 800-63-4, Digital Identity Guidelines (supersedes SP 800-63-3, withdrawn August 1, 2025)",
        "url": "https://www.nist.gov/publications/nist-sp-800-63-4-digital-identity-guidelines",
        "verified": "Opened; NIST publication page. SP 800-63-3 CSRC page states withdrawal and supersession.",
    },
    {
        "id": "NIST-800-207",
        "title": "NIST SP 800-207, Zero Trust Architecture, August 2020",
        "url": "https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-207.pdf",
        "verified": "Downloaded and text-extracted.",
    },
    {
        "id": "ASD-STIG",
        "title": "DISA Application Security and Development STIG (V-2224xx / V-2226xx rule identifiers as published on STIG Viewer)",
        "url": "https://www.stigviewer.com/stig/application_security_and_development/",
        "verified": "Opened; rule identifiers and titles extracted from the page listing.",
    },
    {
        "id": "DAF-ZT",
        "title": "Department of the Air Force Zero Trust Strategy, Version 1.0, and DAF Enterprise Zero Trust Roadmap and Release Notes v2.0 (publication date 23 October 2024)",
        "url": None,
        "verified": "Located by web search on the DAF CIO public site; the site could not be resolved from the assessment environment, so the documents were not opened. Cited by title only. Government to furnish.",
    },
    {
        "id": "DAF-ICAM",
        "title": "DAF ICAM implementation direction (not publicly available)",
        "url": None,
        "verified": "No authoritative public document located. Rows referencing this source are marked 'Needs Government input'.",
    },
]

# ---------------------------------------------------------------------------
# Gaps
# ---------------------------------------------------------------------------

GAPS = [
    {
        "id": "G-01",
        "affected": "API JWT verification — api/source/utils/auth.js:74-81 (verifyToken); api/source/utils/jwksCache.js:182-188 (key filtering)",
        "pillar": "Applications & Workloads",
        "source": "NIST SP 800-53r5 IA-5, SC-23; DoD ZT Capability 3.4 Resource Authorization & Integration; ASD STIG V-222580 (validate session identifiers)",
        "current": "jwt.verify() is called with only an optional {audience} option (auth.js:75-77). No `algorithms` allow-list and no `issuer` option are passed. JWKS keys are filtered to kty RSA/EC/OKP and use=sig (jwksCache.js:182-183), so the library's key-type defaults constrain `alg` (jsonwebtoken ^9.0.2, api/source/package.json:29, derives the accepted set from the key type when no `algorithms` option is passed), but this is implicit rather than an explicit application policy. The expected issuer (STIGMAN_OIDC_PROVIDER, config.js:95) is used only to locate the JWKS URI and is never compared to the token `iss` claim.",
        "gap": "No explicit accepted-algorithm list and no issuer (`iss`) validation in the API. A token from any issuer whose key is reachable through the configured JWKS (for example a multi-tenant IdP or a shared JWKS) would be accepted if audience is not configured.",
        "risk": "M — Signature verification and key-type filtering are present; the residual exposure is cross-issuer or cross-realm token acceptance when the IdP hosts multiple realms or a shared key set, and the absence of an auditable algorithm policy.",
        "action": "Pass an explicit `algorithms` allow-list (for example RS256, PS256, ES256, EdDSA as approved) and `issuer: config.oauth.authority` to jwt.verify(). Add unit tests for wrong-issuer and wrong-alg rejection. Document the resulting contract in docs/installation-and-setup/authentication.rst.",
        "authority": "ISSM (control implementation); Program Office (code change approval)",
        "dependency": "Confirmed list of approved signing algorithms from the Enterprise ICAM PMO / IdP owner; confirmed issuer string for each target environment.",
        "effort": "S",
        "phase": "Phase 1",
    },
    {
        "id": "G-02",
        "affected": "API JWT verification — api/source/utils/auth.js:74-81; api/source/utils/config.js:96 (STIGMAN_JWT_AUD_VALUE)",
        "pillar": "Applications & Workloads",
        "source": "NIST SP 800-53r5 IA-5, SC-23; NIST SP 800-63-4 (assertion audience restriction); DoD ZT Capability 3.4 Resource Authorization & Integration",
        "current": "Audience is validated only when STIGMAN_JWT_AUD_VALUE is set (auth.js:75). The variable has no default (config.js:96). The web client also checks audience only when configured (client/src/js/workers/oidc-worker.js:420).",
        "gap": "Audience restriction is opt-in. In a default deployment, any access token signed by the trusted IdP for any other client/resource is accepted by the API.",
        "risk": "H — Token-audience confusion allows a token minted for a different relying party on the same IdP to be replayed against this API; the check is a configuration switch that is easy to omit and is not detected at startup.",
        "action": "Make audience validation mandatory: fail startup when STIGMAN_JWT_AUD_VALUE is unset unless an explicit insecure-mode flag is present, or default the audience to the API client identifier. Log a startup warning at minimum. Add a unit test for missing-audience rejection.",
        "authority": "ISSM; Program Office",
        "dependency": "Enterprise IdP client registration that issues tokens with a stable `aud` for this API (IdP audience mapper); deployment configuration change in every environment.",
        "effort": "S",
        "phase": "Phase 1",
    },
    {
        "id": "G-03",
        "affected": "API JWT verification — api/source/utils/auth.js:74-81 (no clockTolerance / maxAge options)",
        "pillar": "Applications & Workloads",
        "source": "NIST SP 800-53r5 AC-12, SC-23; ASD STIG V-222580",
        "current": "jwt.verify() enforces `exp` and `nbf` through library defaults; no clockTolerance or maxAge is configured (auth.js:75-77). Token lifetime is therefore entirely IdP-controlled and no application-side ceiling exists.",
        "gap": "The application cannot enforce an organization-defined maximum token lifetime independently of the IdP, and behaviour under clock skew between IdP and API hosts is undocumented.",
        "risk": "L — Expiry is enforced; the exposure is limited to IdP misconfiguration (very long-lived tokens) and undocumented skew handling.",
        "action": "Add an optional `maxAge` ceiling and an explicit small `clockTolerance` (for example 30 s) as configuration with documented defaults; document the required IdP token-lifetime settings in authentication.rst.",
        "authority": "ISSM",
        "dependency": "Government-approved session and token lifetime values (see G-16).",
        "effort": "S",
        "phase": "Phase 2",
    },
    {
        "id": "G-04",
        "affected": "API JWT verification — api/source/utils/auth.js:84-100 (validateToken); no revocation or introspection call",
        "pillar": "User",
        "source": "DoD ZT Capability 1.8 Continuous Authentication (Single Authentication / Periodic Authentication); NIST SP 800-207 §3 (continual evaluation); NIST SP 800-53r5 AC-12",
        "current": "Tokens are validated offline against the cached JWKS (auth.js:51-60, 84-100). No token introspection, revocation list, or back-channel logout handling exists. A token remains valid until `exp` regardless of IdP session state.",
        "gap": "No mechanism to terminate access before token expiry when a user is disabled, a CAC is revoked, or the IdP session is ended.",
        "risk": "M — Exposure window equals the access-token lifetime configured at the IdP; with short-lived tokens the risk is bounded, but the application has no independent control.",
        "action": "Adopt short access-token lifetimes at the IdP as a documented deployment requirement; add optional introspection or back-channel logout support for high-risk deployments; propagate local `status='unavailable'` (UserService.js:338) to reject requests immediately after an administrator disables a user.",
        "authority": "AO (risk acceptance of token-lifetime exposure window); Enterprise ICAM PMO (IdP session policy)",
        "dependency": "Enterprise IdP support for introspection or back-channel logout; approved token lifetime policy.",
        "effort": "M",
        "phase": "Phase 2",
    },
    {
        "id": "G-05",
        "affected": "Local identity store — api/source/utils/auth.js:110-117 (username precedence); api/source/service/UserService.js:345-351, 500-556; api/source/service/migrations/sql/current/10-stigman-tables.sql (`user_data.username` UNIQUE)",
        "pillar": "User",
        "source": "DoD Enterprise ICAM Reference Design (persistent unique identifier / master user record); NIST SP 800-53r5 IA-4, IA-8; ASD STIG V-222522, V-222552; DoD ZT Capability 1.5 Identity Federation & User Credentialing",
        "current": "The API selects an identity from the first present claim in [configured username claim, preferred_username, configured service-name claim, azp, client_id, clientId] (auth.js:110-111) and keys the local record on that string (`user_data.username`, UNIQUE). The `sub` claim is not used as the identity key. No EDIPI/DoD ID or certificate identifier column exists.",
        "gap": "Identity is a mutable, IdP-scoped display name rather than a persistent unique identifier. Username re-use, renames, or IdP migration can silently merge or split user histories and grants.",
        "risk": "H — Username collision across IdP migrations or between a person and an NPE client would transfer collection grants and audit history to the wrong subject.",
        "action": "Add an immutable identity key (for example `sub` plus issuer, or an enterprise persistent identifier such as EDIPI/DoD ID when furnished in the assertion) to `user_data`; migrate existing records with a Government-approved mapping; keep `username` as a display attribute only.",
        "authority": "Enterprise ICAM PMO (attribute standard); Program Office (schema change); AO (migration risk)",
        "dependency": "Enterprise IdP assertion profile that includes a persistent identifier; approved attribute-mapping specification (DAF ICAM direction — Needs Government input).",
        "effort": "L",
        "phase": "Phase 2",
    },
    {
        "id": "G-06",
        "affected": "First-login provisioning — api/source/utils/auth.js:117-140; api/source/service/UserService.js:345-351 (INSERT INTO user_data)",
        "pillar": "User",
        "source": "NIST SP 800-53r5 AC-2, AC-2(1); ASD STIG V-222413, V-222467; DoD ZT Capability 1.5 Organizational Identity Life-Cycle Management",
        "current": "Any subject that presents a valid token with the required scope is inserted into `user_data` on first request (auth.js:117, UserService.js:351). There is no approval step, no allow-list, and no automatic disable on inactivity (`lastAccess` is recorded but not acted on).",
        "gap": "Account creation is implicit and unbounded by anything other than IdP token issuance; the application cannot enforce organization-defined account authorization, and no account-creation audit record distinct from the request log is written.",
        "risk": "M — Acceptable when the IdP client is tightly scoped to authorized users; otherwise every IdP user becomes an application user. Inactivity disable relies entirely on the IdP.",
        "action": "Emit an explicit `account-created` audit event with subject/source/outcome; add an optional configuration to require pre-provisioning or a group/role claim for first login; document that account-lifecycle (disable after inactivity, removal) is enforced by the enterprise IdP and must be verified in the ATO.",
        "authority": "ISSM; Enterprise ICAM PMO",
        "dependency": "Enterprise group/role attribute available in the assertion (G-05); logging changes (G-11).",
        "effort": "M",
        "phase": "Phase 2",
    },
    {
        "id": "G-07",
        "affected": "Non-person entity handling — api/source/utils/auth.js:110-111 (azp/client_id/clientId fallback); api/source/utils/config.js:104 (STIGMAN_JWT_SERVICENAME_CLAIM has no default); docs/installation-and-setup/authentication.rst:28,110",
        "pillar": "User",
        "source": "DoDI 8520.03 §3.4 (NPE authentication) and §3.4.e (NPE authentication as a provisioned user); DoD Enterprise ICAM Reference Design (NPE identity); NIST SP 800-53r5 IA-9",
        "current": "Service accounts are mapped to the same `user_data` table using the client identifier as the username (auth.js:110-111). Documentation states the service-name claim defaults to `clientId` (authentication.rst:28) while the code has no default (config.js:104); the hard-coded fallback list supplies the same behaviour.",
        "gap": "NPEs and persons share one identity namespace and one privilege model; there is no NPE-specific credential policy (certificate-based client authentication, rotation) enforced or documented, and no marker distinguishing NPE records.",
        "risk": "M — An NPE client name equal to a person's username would collide (see G-05); NPE credentials are governed only by the IdP.",
        "action": "Add an `entityType` attribute to local identities derived from the token (client-credentials grant vs. person); require NPE clients to authenticate to the IdP with a DoD-approved certificate credential; align documentation with code for the service-name claim.",
        "authority": "Enterprise ICAM PMO (NPE credential policy); ISSM",
        "dependency": "G-05 persistent identifier; IdP configured for certificate-bound client authentication.",
        "effort": "M",
        "phase": "Phase 2",
    },
    {
        "id": "G-08",
        "affected": "Privilege mapping — api/source/utils/auth.js:142-149; api/source/utils/config.js:106-108 (STIGMAN_JWT_PRIVILEGES_CLAIM default realm_access.roles)",
        "pillar": "User",
        "source": "NIST SP 800-53r5 AC-6, AC-6(1), AC-6(5); DoD ZT Capability 1.2 Conditional User Access (App Based Permissions per Enterprise); ASD STIG V-222429",
        "current": "Application privileges are exactly two string values, `admin` and `create_collection`, read from a configurable claim path defaulting to Keycloak's `realm_access.roles` (auth.js:142-145). Any token from the trusted IdP that carries these strings receives the privilege.",
        "gap": "Privilege is a coarse two-value role list with a Keycloak-specific default path. There is no mapping layer from enterprise groups/attributes to application privileges, and no support for conditional or attribute-based grant of `admin`.",
        "risk": "M — Functionally sound but IdP-specific; migration to an enterprise IdP requires either a custom claim mapper at the IdP or configuration changes in every environment.",
        "action": "Externalise privilege mapping (enterprise group or attribute → application privilege) into configuration or an admin-managed table; document required IdP mappers for the enterprise IdP; keep `realm_access.roles` as a compatible default.",
        "authority": "Enterprise ICAM PMO (group naming and attribute release); Program Office",
        "dependency": "Enterprise IdP group/attribute claim specification (Needs Government input).",
        "effort": "M",
        "phase": "Phase 2",
    },
    {
        "id": "G-09",
        "affected": "Elevated administration and self-grant — api/source/controllers/Collection.js:389-405 (getCollectionInfoAndCheckPermission); api/source/controllers/Collection.js:298; docs/installation-and-setup/data-and-permissions.rst:177-191",
        "pillar": "User",
        "source": "NIST SP 800-53r5 AC-5, AC-6(1), AC-6(9), AC-6(10); DoD ZT Capability 1.4 Privileged Access Management; ASD STIG V-222431, V-222450, V-222454",
        "current": "Users with the `admin` privilege pass `?elevate=true` to bypass collection-grant checks for management operations (Collection.js:389-405). Documentation confirms an elevated admin may grant themselves any role in any collection and states that the accepted control is that elevated request/response bodies are written to the application log (data-and-permissions.rst:189-191). Elevation is per-request and does not require re-authentication.",
        "gap": "No separation of duties between the role that manages grants and the role that consumes collection content; no re-authentication or step-up for privileged operations; no break-glass procedure or dual-authorisation option.",
        "risk": "H — A single `admin` role can obtain full read/write access to any collection by self-grant. The compensating control is after-the-fact log review, which depends on deployment log retention and review (G-12).",
        "action": "Add a configurable policy that (a) denies self-grant by default and requires a second admin, (b) requires step-up re-authentication (fresh `auth_time` or `acr` claim) for `elevate=true`, and (c) emits a distinct `privilege-change` audit event. Document a break-glass procedure for the deployment.",
        "authority": "AO (accept or reject the current compensating control); ISSM (break-glass procedure)",
        "dependency": "IdP support for step-up authentication claims (`acr`/`auth_time`); structured audit events (G-11).",
        "effort": "M",
        "phase": "Phase 1",
    },
    {
        "id": "G-10",
        "affected": "Scope matching — api/source/utils/auth.js:161-185 (validateOauthSecurity); api/source/specification/stig-manager.yaml:10892-10900 (securitySchemes), :3753 and :3767 (security: [] on /op/configuration and /op/definition)",
        "pillar": "Applications & Workloads",
        "source": "NIST SP 800-53r5 AC-3, AC-6; DoD ZT Capability 1.7 Least Privileged Access (Deny User by Default Policy); ASD STIG V-222425",
        "current": "Every operation in the OpenAPI specification declares required `stig-manager:*` scopes except two that declare `security: []`: GET /op/configuration and GET /op/definition (stig-manager.yaml:3753, 3767). validateToken only verifies a token when one is present (auth.js:86-87), so those two operations answer unauthenticated requests; /op/configuration returns the API version, commit, last migration and every row of the `config` table (controllers/Operation.js:8-13; OperationService.js:19-27), and /op/definition returns the OpenAPI document. All other operations are enforced by express-openapi-validator (middlewares.js:111). Granted scopes match if equal or if the granted scope is a prefix of the required scope by colon-separated tokens (auth.js:170-178), so `stig-manager:collection` satisfies `stig-manager:collection:read`.",
        "gap": "Two operations are intentionally unauthenticated and are not identified as public exceptions in the security documentation; the `config` table contents are disclosed to anyone who can reach the API. For authenticated operations the prefix rule means a broad parent scope grants every child operation; there is no documentation of the minimum scope set per role and no test asserting that unexpected scope strings are rejected.",
        "risk": "L — The public operations disclose version and configuration values but no user or assessment data, and the client needs /op/configuration before login; the authenticated path is deliberate and consistent. Residual risk is over-broad scope issuance at the IdP and disclosure of any sensitive value a deployment places in `config`.",
        "action": "Document /op/configuration and /op/definition as the only public operations and add a test that fails if any other operation declares `security: []`; restrict /op/configuration to the keys the client needs before login; publish a least-privilege scope matrix (role → minimum scopes) in authentication.rst; add unit tests for prefix matching and rejection of unrelated scopes; recommend IdP client scope restrictions per client.",
        "authority": "ISSM",
        "dependency": "None (documentation and tests).",
        "effort": "S",
        "phase": "Phase 1",
    },
    {
        "id": "G-11",
        "affected": "Security event logging — api/source/utils/logger.js:79-93 (serializeRequest), 155-183 (transaction/response records); api/source/bootstrap/errorHandlers.js:13-17; api/source/utils/logSocket.js:190-191",
        "pillar": "Visibility & Analytics",
        "source": "NIST SP 800-53r5 AU-2, AU-3, AU-12; ASD STIG V-222450, V-222454, V-222462, V-222463, V-222477; DoD ZT Capability 7.1 Log All Traffic (Log Parsing)",
        "current": "Every request produces a structured JSON record with requestId, date, source IP, method, URL, headers and (in combined mode) response status and operation statistics (logger.js:79-93, 160-171). Application security errors (SmError, including PrivilegeError, OutOfScopeError, NoTokenError) are returned to the client but are not written as distinct error events; only non-application errors are logged at errorHandlers.js:13-17. The HTTP status appears in the transaction record. There is no dedicated event type for logon, logoff, privilege change, grant change, account creation or data export.",
        "gap": "Security-relevant events must be reconstructed from generic transaction records by URL pattern and status code. No first-class audit events exist with subject, object, action, outcome and source fields, which complicates SIEM parsing and AU-6 review.",
        "risk": "M — Data needed for reconstruction is mostly present (subject via userObject, source IP, URL, status) but not normalised; failed authorization is logged only as a transaction with a 403 status.",
        "action": "Add an `audit` event type emitted by the API for: authentication accepted/rejected, authorization denied (scope, privilege, grant), account created/modified/disabled, grant created/modified/deleted, elevated request, data export, and admin operations. Each event carries subject (userId, username, persistent id), object (collectionId/assetId/userId), action, outcome, source IP and requestId. Publish the JSON schema alongside the existing logging schema.",
        "authority": "ISSM (auditable event list per AU-2); Program Office",
        "dependency": "Government-approved auditable-event list; SIEM parser update.",
        "effort": "M",
        "phase": "Phase 1",
    },
    {
        "id": "G-12",
        "affected": "Log retention, protection and review — docs/installation-and-setup/logging.rst:8 (STDOUT JSON); docs/installation-and-setup/data-and-permissions.rst:189-191 (log review as compensating control)",
        "pillar": "Visibility & Analytics",
        "source": "NIST SP 800-53r5 AU-6, AU-9, AU-11; ASD STIG V-222481, V-222482; DoD ZT Capability 7.2 Security Information and Event Management (SIEM)",
        "current": "The application writes JSON to STDOUT only (logging.rst:8). Collection, forwarding, retention, integrity protection and review are deployment responsibilities and are not specified.",
        "gap": "The security model for elevated administration depends on log review, but no requirement for SIEM forwarding, retention period, or review cadence is stated for the deployment.",
        "risk": "M — Without enforced forwarding and review, the compensating control for G-09 does not exist in practice.",
        "action": "Add a deployment security baseline that requires container log forwarding to the enterprise SIEM, retention per Government policy, and a documented review procedure for `elevate=true` transactions and audit events; add SIEM parsing rules for the new audit event type.",
        "authority": "ISSM; AO (retention and review cadence)",
        "dependency": "Enterprise SIEM onboarding; G-11 audit events.",
        "effort": "S",
        "phase": "Phase 1",
    },
    {
        "id": "G-13",
        "affected": "Sensitive data in logs — api/source/utils/logger.js:62-76 (sanitizeHeaders decodes bearer payload), 81-83 (accessToken added in combined mode), 91 (request body logged for elevate or log level 4)",
        "pillar": "Visibility & Analytics",
        "source": "ASD STIG V-222444 (must not write sensitive data into logs); NIST SP 800-53r5 AU-3(3), SC-28",
        "current": "The bearer token itself is replaced by `authorization: true`, but the decoded token payload (all claims) is attached to the request record as `headers.accessToken` in every mode (logger.js:68-69, 81-83). Full request bodies are logged for elevated requests and at log level 4 (logger.js:91), and full response bodies in combined mode (logger.js:168).",
        "gap": "Logs contain every identity claim released by the IdP (email, names, roles, any custom attributes) and, for elevated requests, complete request/response payloads. If the enterprise IdP releases additional PII attributes, they will be written to logs unfiltered.",
        "risk": "M — Signature is stripped so tokens cannot be replayed from logs, but PII exposure and log volume grow with the enterprise attribute set.",
        "action": "Replace the full decoded payload with a fixed subject block (sub/persistent id, username, azp, scope, exp, jti); keep body logging for elevated requests but redact configured sensitive fields; document the log data classification.",
        "authority": "ISSM; Privacy Officer (PII in logs)",
        "dependency": "Enterprise attribute release list (Needs Government input).",
        "effort": "S",
        "phase": "Phase 2",
    },
    {
        "id": "G-14",
        "affected": "Web client token handling — client/src/js/workers/oidc-worker.js:55 (logs authorization code and PKCE verifier), :542 (logs full token response)",
        "pillar": "User",
        "source": "ASD STIG V-222444, V-222577 (must not expose session identifiers); NIST SP 800-53r5 IA-5(7), SC-28",
        "current": "The OIDC worker writes the authorization code and PKCE code_verifier (oidc-worker.js:55) and the complete token endpoint response including access and refresh tokens (oidc-worker.js:542) to the browser console.",
        "gap": "Credentials are exposed in browser developer tooling and in any console-capture mechanism (browser telemetry, screen recording, support tooling).",
        "risk": "M — Exploitation requires access to the user's browser session or console logs; refresh tokens in the console extend the exposure beyond the access-token lifetime.",
        "action": "Remove token, code and verifier values from console output; log only event names and timestamps. Add a unit test or lint rule that fails on logging of `tokensResponse`, `code`, or `codeVerifier`.",
        "authority": "Program Office",
        "dependency": "None.",
        "effort": "S",
        "phase": "Phase 1",
    },
    {
        "id": "G-15",
        "affected": "Web client authorization flow — client/src/js/workers/oidc-worker.js:205 (strict PKCE metadata check), :266-267 (S256 challenge), :63 (code_verifier), :114-119 (logout returns end_session_endpoint only), :519-525 (clearTokens); client/src/js/init.js:217-223 (page logout wrapper); api/source/utils/config.js:45 (STIGMAN_CLIENT_STRICT_PKCE)",
        "pillar": "User",
        "source": "NIST SP 800-63-4 (federation assertion handling); ASD STIG V-222391 (logoff capability), V-222578; NIST SP 800-53r5 AC-12(1)",
        "current": "Authorization Code with PKCE S256 is always used: every authorization request carries code_challenge_method=S256 (oidc-worker.js:266-267) and every code exchange carries code_verifier (oidc-worker.js:63). STIGMAN_CLIENT_STRICT_PKCE=false (config.js:45) only skips the check that provider metadata advertises S256 (oidc-worker.js:205); it does not disable PKCE. Tokens are held in shared-worker memory, not in storage. The worker logout handler returns the provider end_session_endpoint and does not call clearTokens (oidc-worker.js:114-119); the page wrapper nulls its own token fields and redirects (init.js:217-223). clearTokens with broadcast exists and is used on refresh failure (oidc-worker.js:329, 569, 583).",
        "gap": "Logout does not clear the access and refresh tokens held by the shared worker and does not revoke the refresh token at the IdP. While another tab keeps the shared worker alive, that tab can continue to obtain the unchanged access token after a logout in a sibling tab; local termination relies on token expiry and on the IdP end-session redirect.",
        "risk": "L — Requires an already-authenticated browser with a second open tab; the access token still expires at `exp` and the IdP session is ended by the redirect. Contained to the client.",
        "action": "In the worker logout handler call clearTokens(true) before returning the redirect and test the multi-tab case; call the IdP revocation endpoint (if advertised) for the refresh token on logout; document the required IdP client settings (public client, PKCE required, no implicit flow).",
        "authority": "ISSM; Program Office (client change)",
        "dependency": "None.",
        "effort": "S",
        "phase": "Phase 1",
    },
    {
        "id": "G-16",
        "affected": "Session lifetime and idle timeout — client/src/js/workers/oidc-worker.js:335-410 (refresh timers), :457-490 (validateClaims, idle timeout by privilege), :575-585; api/source/utils/config.js:26-36 (STIGMAN_CLIENT_USER_TIMEOUT, STIGMAN_CLIENT_ADMIN_TIMEOUT default 0)",
        "pillar": "User",
        "source": "NIST SP 800-53r5 AC-11, AC-12; ASD STIG V-222389 (15-minute non-privileged idle), V-222390 (10-minute admin idle); DoD ZT Capability 1.8 Continuous Authentication",
        "current": "The client implements separate idle timeouts for admin and non-admin users, but both default to 0 (disabled) unless STIGMAN_CLIENT_USER_TIMEOUT / STIGMAN_CLIENT_ADMIN_TIMEOUT are set (config.js:26-36, oidc-worker.js:471-476). Access-token refresh continues automatically while the refresh token is valid (oidc-worker.js:335-410). Idle timeout is enforced client-side only; the API has no session concept beyond token expiry.",
        "gap": "Idle timeouts are disabled by default and are enforced only in the browser; the API cannot enforce an inactivity limit independently of the IdP's refresh-token policy.",
        "risk": "M — Default configuration does not meet the STIG idle-timeout values; a deployment must remember to set both variables and configure matching IdP session limits.",
        "action": "Set secure defaults (15 min user, 10 min admin) and require explicit opt-out; document the paired IdP settings (SSO idle, refresh-token lifetime, access-token lifetime) that make the server-side limit effective; consider adding `auth_time`/`iat` age checks at the API for privileged operations.",
        "authority": "ISSM; AO (approve timeout values)",
        "dependency": "Government-approved session lifetime values; IdP configuration control.",
        "effort": "S",
        "phase": "Phase 1",
    },
    {
        "id": "G-17",
        "affected": "CAC/PIV and MFA path — docs/installation-and-setup/installation-and-setup.rst:57-62 (reverse proxy required for mTLS/CAC/PKI); api/source/bootstrap/server.js:45-48 (native TLS without client certificate options)",
        "pillar": "User",
        "source": "DoDI 8520.03 §3.2.b-c, §3.3 (person entity authentication; DoD-approved PKI / AAL2-AAL3 assertions); NIST SP 800-53r5 IA-2(1), IA-2(2), IA-2(12); ASD STIG V-222523, V-222526, V-222550, V-222552, V-222559; DoD ZT Capability 1.3 MFA (Organizational MFA/IDP)",
        "current": "The application performs no direct authentication; it relies entirely on OIDC assertions. CAC/PIV authentication, certificate path validation and revocation checking occur at the IdP or a reverse proxy in front of it (installation-and-setup.rst:57-62). The API does not inspect `acr`, `amr` or `auth_time` claims, so it cannot distinguish a CAC-authenticated session from a password session issued by the same IdP.",
        "gap": "The application has no assurance-level awareness. It cannot require or verify that the assertion was produced by a DoD-approved PKI credential, and the CAC → IdP → application flow is undocumented for the enterprise IdP.",
        "risk": "H — Meeting DoDI 8520.03 for moderate/high-risk resources depends entirely on IdP configuration that the application neither checks nor documents; a mis-configured IdP realm with password login enabled would be indistinguishable to the API.",
        "action": "Document the CAC/PIV path end-to-end (browser → IdP X.509 authenticator → OIDC assertion with `amr`/`acr` → API). Add optional API enforcement of a required `acr`/`amr` value (configurable) and expose it in the audit event. Confirm the IdP is an approved DoD IdP or reverse-proxy IdP per DoDI 8520.03 §3.6.",
        "authority": "AO (resource risk level per DoDI 8520.03 §3.3); Enterprise ICAM PMO (approved IdP and assertion profile)",
        "dependency": "Enterprise IdP assertion profile including authentication-context claims (Needs Government input); DAF ICAM direction on approved IdPs.",
        "effort": "M",
        "phase": "Phase 2",
    },
    {
        "id": "G-18",
        "affected": "Single IdP client / realm configuration — api/source/utils/config.js:37, 89, 95 (default authority http://localhost:8080/realms/stigman); api/source/specification/stig-manager.yaml:10895 (openIdConnectUrl literal); client/src/js/Env.js.example",
        "pillar": "Applications & Workloads",
        "source": "DoD Enterprise ICAM Reference Design (enterprise IdP federation); NIST SP 800-53r5 IA-8; DoD ZT Capability 1.9 Integrated ICAM Platform (Enterprise PKI/IDP Pt1); ASD STIG V-222560",
        "current": "One OIDC authority is configured for the API, one for the web client and one for the OpenAPI UI (config.js:37, 89, 95). Defaults point at a local Keycloak realm named `stigman`. The OpenAPI document embeds a literal Keycloak discovery URL (stig-manager.yaml:10895). Only one issuer/JWKS is supported at a time.",
        "gap": "Single-issuer design with Keycloak-specific defaults. Federation scenarios (enterprise IdP plus a mission-partner IdP, or migration with an overlap period) are not supported without a broker in front of the application.",
        "risk": "M — Enterprise integration is feasible by pointing the authority at the enterprise IdP or a broker, but multi-issuer operation and issuer pinning (G-01) are absent, and defaults are non-production values.",
        "action": "Remove non-production defaults from production images (fail fast when unset); support a small list of trusted issuers with per-issuer JWKS and audience; generate the OpenAPI `openIdConnectUrl` from configuration at startup.",
        "authority": "Enterprise ICAM PMO (federation pattern: direct vs. broker); Program Office",
        "dependency": "Decision on federation topology; G-01 issuer validation.",
        "effort": "M",
        "phase": "Phase 3",
    },
    {
        "id": "G-19",
        "affected": "Attribute-based access control — api/source/controllers/Collection.js:389-405 (grant/role check); api/source/utils/roles.js:1-6 (numeric roles Restricted=1 … Owner=4); api/source/service/migrations/sql/current/10-stigman-tables.sql (collection_grant, user_group)",
        "pillar": "Applications & Workloads",
        "source": "DoD ZT Capability 3.4 Resource Authorization & Integration (Enrich Attributes for Resource Authorization Pt1); NIST SP 800-207 §3.1 (policy engine / policy administrator); NIST SP 800-53r5 AC-3(13) attribute-based access control",
        "current": "Authorization is RBAC: collection grants assign one of four ordered roles to a user or user group, with optional ACLs within a collection (Collection.js:389-405, roles.js). Decisions are made in controllers and services using locally stored grants; there is no policy decision point and no use of enterprise attributes (organisation, clearance, duty position) at decision time.",
        "gap": "No externalised policy decision point and no attribute inputs beyond the local grant table; ABAC or conditional access (device posture, location, risk score) cannot be expressed without code change.",
        "risk": "M — RBAC is adequate for current use; Target-level ZT activities for resource authorization enrichment are not met.",
        "action": "Introduce an authorization abstraction (policy enforcement point) around getCollectionInfoAndCheckPermission and the user/grant controllers that can consult an external policy decision point (for example OPA or the enterprise PDP) with token attributes and request context; keep local RBAC as the fallback policy.",
        "authority": "Enterprise ICAM PMO (enterprise PDP/attribute service availability); Program Office; AO",
        "dependency": "Enterprise attribute source and PDP available to the application enclave; G-05 and G-08 attribute mapping.",
        "effort": "L",
        "phase": "Phase 3",
    },
    {
        "id": "G-20",
        "affected": "API transport security — api/source/bootstrap/server.js:10-48 (HTTPS only when STIGMAN_API_TLS_KEY_FILE and STIGMAN_API_TLS_CERT_FILE are set); docs/installation-and-setup/installation-and-setup.rst:106",
        "pillar": "Network & Environment",
        "source": "NIST SP 800-53r5 SC-8, SC-8(1), SC-23; ASD STIG V-222396, V-222397, V-222584",
        "current": "Native HTTPS is optional; the server falls back to plain HTTP when TLS files are not configured (server.js:45-48). Documentation requires HTTPS for non-localhost use and recommends a reverse proxy (installation-and-setup.rst:106). No minimum TLS version or cipher policy is set in code (Node defaults apply).",
        "gap": "Transport protection depends on deployment; the application does not enforce TLS 1.2+ or DoD-approved certificate authorities itself and does not refuse to start without TLS.",
        "risk": "M — Standard for containerised services behind a terminating proxy, but a direct-exposure deployment could run unencrypted.",
        "action": "Add a production mode that refuses plain HTTP unless an explicit proxy-terminated flag is set; pin minVersion TLSv1.2 (or 1.3) and FIPS-approved cipher suites when native TLS is used; document the DoD PKI trust store requirement for the proxy or native listener.",
        "authority": "ISSM; AO (TLS termination point)",
        "dependency": "Deployment architecture decision (native TLS vs. proxy/ingress).",
        "effort": "S",
        "phase": "Phase 1",
    },
    {
        "id": "G-21",
        "affected": "Database connection identity — api/source/service/utils.js:187-197 (TLS only when CA/cert/key configured); api/source/utils/config.js:73-79 (STIGMAN_DB_PASSWORD); docs/installation-and-setup/db.rst:125-136 (client certificate authentication)",
        "pillar": "Network & Environment",
        "source": "DoD ZT Capability 5.x Network & Environment (data-flow protection) and 2.x Device (workload identity as applied to service-to-service); DoDI 8520.03 §3.4.a (NPE mutually authenticated transactions); NIST SP 800-53r5 SC-8, IA-9; ASD STIG V-222534",
        "current": "MySQL TLS is enabled only when at least one of CA, certificate or key file is configured (utils.js:187-197). The API supports X.509 client-certificate authentication to MySQL as an alternative to a password (db.rst:125-136). Default configuration is a static password in an environment variable with no TLS.",
        "gap": "Mutual TLS between API and database is available but optional; the default is password-based, unencrypted database access.",
        "risk": "M — Within a private network segment the exposure is limited; the default does not meet the mutual-authentication expectation for service-to-service traffic.",
        "action": "Make database TLS with server-certificate verification the default, and adopt X.509 client-certificate authentication for the API service identity; fail startup when neither TLS nor an explicit insecure flag is present.",
        "authority": "ISSM; Program Office",
        "dependency": "Enclave PKI able to issue service certificates; database configured to require TLS.",
        "effort": "M",
        "phase": "Phase 2",
    },
    {
        "id": "G-22",
        "affected": "Secrets and workload identity in deployment assets — api/source/utils/config.js:74 (STIGMAN_DB_PASSWORD), :63-66 and :76-79 (file paths for TLS material); Dockerfile; docs/installation-and-setup/",
        "pillar": "Device",
        "source": "DoD ZT Capability 2.x Device / 3.x Applications & Workloads (workload identity, secrets handling); NIST SP 800-53r5 IA-5(7), SC-12, SC-28; ASD STIG V-222642 (no embedded authentication data)",
        "current": "No credentials are embedded in source; all secrets arrive as environment variables or mounted files (config.js:63-79). No secrets-manager or workload-identity integration exists; rotation is a deployment concern. Container images run the API directly from the Dockerfile with no secret retrieval step.",
        "gap": "Secrets lifecycle (issuance, rotation, revocation) and workload identity are entirely outside the application; no guidance ties them to an enterprise secrets manager or service mesh identity.",
        "risk": "L — Environment-variable injection is the common container pattern; risk depends on the orchestrator's secret handling.",
        "action": "Document a reference deployment that sources STIGMAN_DB_PASSWORD (or preferably the client certificate) and TLS keys from the platform secrets manager with rotation; adopt certificate-based database identity (G-21) to eliminate the password entirely.",
        "authority": "ISSM; Platform/Hosting owner",
        "dependency": "Platform secrets manager and PKI issuance for workloads.",
        "effort": "S",
        "phase": "Phase 2",
    },
    {
        "id": "G-23",
        "affected": "Data export events — api/source/controllers/Collection.js:105-108 (exportCollections), :1030-1037 (exportToCollection operation in stig-manager.yaml); checklist download operations (stig-manager.yaml:227, 256, 977)",
        "pillar": "Data",
        "source": "NIST SP 800-53r5 AU-2, AC-4, AC-21; ASD STIG V-222471 (log user actions involving access to data); DoD ZT Capability 4.x Data (data monitoring)",
        "current": "Collection export, checklist download and cross-collection copy are ordinary authenticated operations recorded only as request/transaction log entries (logger.js:155-183). There is no data classification or labelling of exported artifacts and no export-specific audit event.",
        "gap": "Bulk data egress is indistinguishable from routine reads in the logs; no export approval or marking control exists.",
        "risk": "L — Data is STIG compliance data whose sensitivity is determined by the Government; the gap is visibility rather than enforcement.",
        "action": "Emit `data-export` audit events (subject, collection, format, record count); add optional export marking/banner text from configuration; include export events in SIEM alerting rules.",
        "authority": "Data Owner / ISSM (classification of compliance data)",
        "dependency": "G-11 audit events; Government data-classification decision.",
        "effort": "S",
        "phase": "Phase 2",
    },
    {
        "id": "G-24",
        "affected": "Insecure-token allowance — api/source/utils/auth.js:44-49 (checkInsecureKid); api/source/utils/config.js:4, 97-99 (STIGMAN_DEV_ALLOW_INSECURE_TOKENS, insecureKids list)",
        "pillar": "Applications & Workloads",
        "source": "NIST SP 800-53r5 CM-7, IA-5; ASD STIG V-222662 (default credentials), V-222642",
        "current": "Tokens signed with a known test key ID are rejected unless STIGMAN_DEV_ALLOW_INSECURE_TOKENS=true (auth.js:45-46). The known insecure kid is hard-coded (config.js:4). This is a deliberate guard against shipping the test IdP key into production.",
        "gap": "The guard is positive, but the bypass is a plain environment flag with no startup warning and no audit event when enabled.",
        "risk": "L — Requires deliberate misconfiguration; a startup warning would make it visible.",
        "action": "Log a persistent WARN at startup and in every audit event when insecure tokens are allowed; exclude the flag from production container defaults; add a unit test that the insecure kid is rejected by default.",
        "authority": "ISSM",
        "dependency": "None.",
        "effort": "S",
        "phase": "Phase 1",
    },
    {
        "id": "G-25",
        "affected": "Automation of identity governance — api/source/controllers/User.js:25-31 (elevate required for user management); api/source/service/UserService.js:338 (status unavailable); no scheduled job or SCIM/provisioning API",
        "pillar": "Automation & Orchestration",
        "source": "DoD ZT Capability 6.x Automation & Orchestration (policy and identity automation); NIST SP 800-53r5 AC-2(1), AC-2(3), AC-2(4); ASD STIG V-222411, V-222415",
        "current": "User status changes and grant management are manual API operations by an elevated admin (User.js:25-31). No SCIM endpoint, no inbound deprovisioning hook, and no scheduled inactivity review exist. `lastAccess` is recorded (UserService.js:505) but nothing acts on it.",
        "gap": "Joiner/mover/leaver events at the enterprise IdP are not propagated to local grants; orphaned grants persist until an administrator removes them.",
        "risk": "M — Disabled enterprise users cannot obtain tokens, so access is blocked, but their grants and history remain and are re-activated if the username is re-used (G-05).",
        "action": "Add a configurable inactivity job that sets `status='unavailable'` after N days without access and emits an audit event; add an administrative bulk-reconciliation endpoint or SCIM-style deprovisioning hook the enterprise IdP or an orchestrator can call.",
        "authority": "Enterprise ICAM PMO (provisioning integration pattern); ISSM (inactivity threshold)",
        "dependency": "G-05 persistent identifier; enterprise provisioning or event feed availability.",
        "effort": "M",
        "phase": "Phase 3",
    },
    {
        "id": "G-26",
        "affected": "DAF-specific ICAM alignment — whole application; no repository evidence (policy source not public)",
        "pillar": "User",
        "source": "Needs Government input — DAF ICAM implementation direction and DAF Enterprise Zero Trust Roadmap (documents located by title only; not opened from the assessment environment)",
        "current": "Publicly available material describes DAF enterprise identity services at a high level only (an authoritative identity data service and a published DAF Zero Trust strategy and roadmap). No public document specifies the DAF-required IdP, assertion profile, attribute set, or identifier for applications of this type.",
        "gap": "The assessment cannot confirm alignment with DAF-specific ICAM requirements. Rows G-05, G-08, G-17 and G-18 are structured so the Government-furnished direction replaces the assumptions recorded here.",
        "risk": "M — Uncertainty rather than a known defect; the integration design cannot be finalised until direction is furnished.",
        "action": "Government to furnish the DAF ICAM integration specification (approved IdP endpoints, client registration process, assertion claims including persistent identifier and authentication context, attribute release, logging destination). Re-baseline G-05, G-08, G-17, G-18 against it.",
        "authority": "Enterprise ICAM PMO; Program Office",
        "dependency": "Receipt of Government-furnished DAF ICAM direction.",
        "effort": "S",
        "phase": "Phase 0",
    },
]

# ---------------------------------------------------------------------------
# NIST SP 800-53 Rev. 5 control crosswalk
# ---------------------------------------------------------------------------

CROSSWALK_STATUSES = ("Satisfied", "Partially", "Not satisfied", "Needs Government input")

CROSSWALK = [
    ("IA-2", "Identification and Authentication (Organizational Users)", "Partially",
     "All API operations require a bearer token validated against the IdP JWKS (auth.js:84-100) except GET /op/configuration and GET /op/definition, which declare security: [] (stig-manager.yaml:3753, 3767). Identification is by username claim, not persistent identifier (auth.js:110-111).", "G-05, G-10, G-17"),
    ("IA-2(1)", "MFA to Privileged Accounts", "Needs Government input",
     "Application does not authenticate directly; MFA is an IdP property. No `acr`/`amr` check in API.", "G-17"),
    ("IA-2(2)", "MFA to Non-Privileged Accounts", "Needs Government input",
     "As IA-2(1).", "G-17"),
    ("IA-2(12)", "Acceptance of PIV Credentials", "Needs Government input",
     "PIV/CAC acceptance occurs at the IdP or reverse proxy (installation-and-setup.rst:57-62); application has no visibility.", "G-17"),
    ("IA-4", "Identifier Management", "Not satisfied",
     "Local identifier is the mutable username string; no persistent unique identifier stored (10-stigman-tables.sql user_data).", "G-05"),
    ("IA-5", "Authenticator Management", "Partially",
     "Signature verification with JWKS rotation (jwksCache.js); no explicit alg/issuer policy (auth.js:74-81); audience optional (config.js:96).", "G-01, G-02, G-24"),
    ("IA-8", "Identification and Authentication (Non-Organizational Users)", "Partially",
     "Any IdP-issued identity is accepted and auto-provisioned; distinction between organizational and non-organizational users depends on IdP.", "G-06, G-18"),
    ("IA-9", "Service Identification and Authentication", "Partially",
     "NPE clients map to users via azp/client_id (auth.js:110-111); DB client-certificate authentication available but optional (db.rst:125-136).", "G-07, G-21"),
    ("AC-2", "Account Management", "Partially",
     "Accounts auto-created at first login (UserService.js:351); status field supports disable (UserService.js:338); no inactivity automation.", "G-06, G-25"),
    ("AC-3", "Access Enforcement", "Partially",
     "OpenAPI scope enforcement on every operation (middlewares.js:111, auth.js:161-185) and collection-grant checks (Collection.js:389-405), with two documented-in-spec public exceptions: /op/configuration and /op/definition (stig-manager.yaml:3753, 3767) return version, `config` table rows and the API definition without authentication.", "G-10"),
    ("AC-5", "Separation of Duties", "Not satisfied",
     "Single `admin` privilege can self-grant any collection role (data-and-permissions.rst:189-191).", "G-09"),
    ("AC-6", "Least Privilege", "Partially",
     "Four-level collection roles and scoped API operations; elevation is per-request and broad.", "G-08, G-09, G-10"),
    ("AC-6(1)", "Authorize Access to Security Functions", "Partially",
     "Security functions require `admin` + `elevate=true` (User.js:25-26); no step-up authentication.", "G-09"),
    ("AC-6(9)", "Log Use of Privileged Functions", "Partially",
     "Elevated requests log full request/response bodies (logger.js:91, 160-171); no distinct audit event type.", "G-09, G-11"),
    ("AC-6(10)", "Prohibit Non-Privileged Users from Executing Privileged Functions", "Satisfied",
     "InvalidElevationError when non-admin requests elevate (auth.js:147-148); PrivilegeError on user management without elevate (User.js:26).", ""),
    ("AC-7", "Unsuccessful Logon Attempts", "Needs Government input",
     "Logon attempts occur at the IdP; application never sees credentials.", "G-17"),
    ("AC-11", "Device Lock", "Partially",
     "Client idle timeout exists but defaults to disabled (config.js:26-36).", "G-16"),
    ("AC-12", "Session Termination", "Partially",
     "Logout returns the IdP end_session_endpoint without clearing worker-held tokens (oidc-worker.js:114-119); no refresh-token revocation; access token valid until exp.", "G-04, G-15, G-16"),
    ("AC-17", "Remote Access", "Partially",
     "HTTPS optional in code (server.js:45-48); documentation requires HTTPS for non-localhost.", "G-20"),
    ("AU-2", "Event Logging", "Partially",
     "All requests/responses logged as JSON (logger.js:100-183); no first-class security events for logon, privilege or grant change, export.", "G-11, G-23"),
    ("AU-3", "Content of Audit Records", "Partially",
     "Records include time, source IP, method/URL, requestId, status, user id via operation stats; subject/object/outcome not normalised.", "G-11, G-13"),
    ("AU-6", "Audit Record Review, Analysis, and Reporting", "Needs Government input",
     "Review is a deployment responsibility; documentation relies on it as the compensating control for self-grant.", "G-12"),
    ("AU-12", "Audit Record Generation", "Partially",
     "Generation is centralised in logger.js; event set is generic rather than the AU-2 defined list.", "G-11"),
    ("SC-8", "Transmission Confidentiality and Integrity", "Partially",
     "TLS available for API (server.js) and DB (utils.js:187-197) but both optional.", "G-20, G-21"),
    ("SC-23", "Session Authenticity", "Partially",
     "Signed JWT with kid lookup and PKCE; missing issuer/audience-by-default checks.", "G-01, G-02, G-03"),
]

# ---------------------------------------------------------------------------
# ZT pillar summary (as-is / target narrative; counts are derived by the
# generator from GAPS and must not be typed here)
# ---------------------------------------------------------------------------

PILLAR_SUMMARY = [
    ("User",
     "OIDC bearer authentication delegated to a single IdP; username-keyed local identities; two-value privilege model; per-request elevation with self-grant; client-side idle timeout disabled by default.",
     "Enterprise IdP federation with persistent identifier and authentication-context claims; PAM-style step-up for elevation; enforced idle/session limits; NPE identities distinguished."),
    ("Device",
     "No device identity or posture input; secrets and TLS material injected by the platform.",
     "Workload identity from enclave PKI/secrets manager; device posture available to the PDP as an authorization attribute (via enterprise IdP conditional access)."),
    ("Applications & Workloads",
     "Scope-per-operation enforcement via OpenAPI; RBAC grants; signature verification with optional audience; single-issuer configuration with non-production defaults.",
     "Explicit alg/issuer/audience policy; multi-issuer trust list; PEP abstraction able to call an enterprise PDP with enriched attributes."),
    ("Data",
     "Exports and downloads logged as generic transactions; no marking.",
     "Export audit events and configurable marking; SIEM rules for bulk egress."),
    ("Network & Environment",
     "TLS optional for API and DB; mTLS to DB supported but not default.",
     "TLS enforced for API listener or documented proxy termination; mTLS/certificate identity to DB by default."),
    ("Automation & Orchestration",
     "Manual user status and grant management; no provisioning integration.",
     "Inactivity automation, deprovisioning hook, reconciliation with enterprise identity events."),
    ("Visibility & Analytics",
     "Structured JSON request/transaction logs to STDOUT; decoded token claims in every record; deployment-owned forwarding.",
     "Normalised audit events (subject/object/action/outcome/source) with PII minimisation; mandatory SIEM forwarding and review procedures."),
]

# ---------------------------------------------------------------------------
# Roadmap
# ---------------------------------------------------------------------------

ROADMAP = [
    ("Phase 0", "Mobilise and baseline",
     "Receive Government-furnished DAF ICAM direction; confirm resource risk level per DoDI 8520.03 §3.3; confirm approved IdP; agree auditable-event list; establish test environment with the approved IdP.",
     "None (entry point).",
     "Enterprise ICAM PMO: furnish IdP, assertion profile and attribute release. AO: resource risk level. ISSM: auditable events."),
    ("Phase 1", "Harden the existing contract",
     "Mandatory audience; explicit algorithms and issuer; secure timeout defaults; audit event type; SIEM forwarding baseline; remove console token logging; TLS production mode; insecure-token startup warning; scope matrix and tests; self-grant policy and step-up design.",
     "Phase 0 decisions on algorithms, issuer strings, audience, timeout values.",
     "ISSM/Program Office: approve code changes. AO: accept or reject self-grant compensating control."),
    ("Phase 2", "Enterprise identity integration",
     "Persistent identifier in user_data with migration; NPE entity type and certificate-bound clients; privilege mapping from enterprise groups; acr/amr enforcement option; token lifetime ceilings; DB mTLS default; secrets-manager reference deployment; log PII minimisation; export events.",
     "Phase 1 complete; enterprise IdP test realm issuing the agreed claims; enclave PKI for service certificates.",
     "Enterprise ICAM PMO: identifier and group standard. AO: migration risk. Privacy Officer: log attribute set."),
    ("Phase 3", "Policy externalisation and federation",
     "PEP abstraction with optional enterprise PDP; multi-issuer trust list; inactivity automation and deprovisioning hook; remove Keycloak-specific defaults from production images.",
     "Phase 2 attribute mapping; enterprise PDP/attribute service reachable from the enclave.",
     "Enterprise ICAM PMO: PDP pattern and federation topology. Program Office: scope."),
    ("Phase 4", "Validate and authorise",
     "Execute the ICAM test plan in the Government-approved environment; SIEM rule validation; ATO evidence package; residual-risk acceptance.",
     "Phases 1-3 delivered to the test environment.",
     "AO: authorisation decision and residual-risk acceptance. ISSM: test witness and evidence."),
]

# ---------------------------------------------------------------------------
# Method
# ---------------------------------------------------------------------------

METHOD = [
    ("Assessment type", "Source-code and documentation review of the repository at the baseline commit; no runtime testing against a Government environment."),
    ("Baseline commit", BASELINE_COMMIT),
    ("Scope", "Authentication (OIDC/JWT), authorization (scopes, grants, elevation), auditability, session and credential handling, privileged access, legacy patterns, workload identity and transport security."),
    ("Evidence convention", "path:line references are to files in this repository at the baseline commit. Line numbers drift with edits; re-verify before citing externally."),
    ("Risk scale", "H = exploitable weakness or non-compliance likely to block authorization; M = weakness with a compensating control or bounded exposure; L = hardening or documentation item."),
    ("Effort scale", "S = under one engineering week; M = one to four weeks; L = more than four weeks or requires schema/data migration."),
    ("Crosswalk statuses", " / ".join(CROSSWALK_STATUSES)),
    ("DAF ICAM direction", "Not publicly available. Rows citing it are marked 'Needs Government input' and are to be re-baselined when direction is furnished."),
    ("Source verification", "Each URL in the Sources sheet was opened from the assessment environment and matched to the cited title; sources that could not be opened are listed without a URL."),
    ("Reproducibility", "python3 docs/security/icam-zero-trust/scripts/icam_gap_register.py regenerates the workbook from this data file; --check verifies the Markdown assessment stays synchronised."),
]
