#!/usr/bin/env python3
"""
DISA STIG XCCDF Parser
======================
Parses DISA Security Technical Implementation Guide (STIG) XCCDF XML files
and extracts structured rule data including V-numbers, severity, check/fix
content, CCI identifiers, and NIST 800-53 control mappings.

Usage:
    python stig_parser.py <xccdf_file.xml> [--output rules.json] [--summary]

Output:
    JSON file containing all parsed STIG rules with metadata.

Author: Generated by Devin (Cognition AI) for DISA STIG remediation automation.
"""

import argparse
import html
import json
import re
import sys
import xml.etree.ElementTree as ET
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Optional

try:
    from defusedxml import ElementTree as SafeET
except ImportError:
    SafeET = None


# CCI to NIST 800-53 control mapping (subset covering common RHEL 9 STIG controls)
CCI_TO_NIST = {
    "CCI-000015": "AC-2",
    "CCI-000017": "AC-2(1)",
    "CCI-000018": "AC-2(2)",
    "CCI-000044": "AC-7",
    "CCI-000048": "AC-8",
    "CCI-000054": "AC-10",
    "CCI-000056": "AC-11(1)",
    "CCI-000057": "AC-11",
    "CCI-000058": "AC-11(1)",
    "CCI-000060": "AC-11(1)",
    "CCI-000067": "AC-17(1)",
    "CCI-000068": "AC-17(2)",
    "CCI-000169": "AU-12",
    "CCI-000170": "AU-12",
    "CCI-000171": "AU-12",
    "CCI-000172": "AU-12",
    "CCI-000130": "AU-3",
    "CCI-000131": "AU-3",
    "CCI-000132": "AU-3",
    "CCI-000133": "AU-3",
    "CCI-000134": "AU-3",
    "CCI-000135": "AU-3(1)",
    "CCI-000139": "AU-5",
    "CCI-000140": "AU-5(1)",
    "CCI-000162": "AU-9",
    "CCI-000163": "AU-9",
    "CCI-000164": "AU-9",
    "CCI-000171": "AU-12",
    "CCI-000172": "AU-12",
    "CCI-000185": "IA-5(2)",
    "CCI-000186": "IA-5(2)",
    "CCI-000187": "IA-5(2)",
    "CCI-000192": "IA-5(1)",
    "CCI-000193": "IA-5(1)",
    "CCI-000194": "IA-5(1)",
    "CCI-000195": "IA-5(1)",
    "CCI-000196": "IA-5(1)",
    "CCI-000197": "IA-5(1)",
    "CCI-000198": "IA-5(1)",
    "CCI-000199": "IA-5(1)",
    "CCI-000200": "IA-5(1)",
    "CCI-000205": "IA-5(1)",
    "CCI-000213": "AC-3",
    "CCI-000366": "CM-6",
    "CCI-000382": "CM-7",
    "CCI-000803": "IA-7",
    "CCI-000877": "MA-4",
    "CCI-001199": "SC-28",
    "CCI-001314": "SI-11",
    "CCI-001398": "AC-2(4)",
    "CCI-001403": "AC-2(4)",
    "CCI-001404": "AC-2(4)",
    "CCI-001453": "AC-17(2)",
    "CCI-001494": "AU-9",
    "CCI-001496": "AU-9(3)",
    "CCI-001619": "IA-5(1)",
    "CCI-001682": "AC-2(2)",
    "CCI-001683": "AC-2(2)",
    "CCI-001684": "AC-2(2)",
    "CCI-001749": "CM-5(3)",
    "CCI-001774": "CM-7(5)",
    "CCI-001849": "AU-4",
    "CCI-001851": "AU-4(1)",
    "CCI-001855": "AU-5(1)",
    "CCI-001856": "AU-5(1)",
    "CCI-001857": "AU-5(1)",
    "CCI-001858": "AU-5(1)",
    "CCI-002038": "IA-11",
    "CCI-002165": "AC-3(4)",
    "CCI-002169": "AC-3(4)",
    "CCI-002233": "AC-6(8)",
    "CCI-002234": "AC-6(9)",
    "CCI-002235": "AC-6(10)",
    "CCI-002238": "AC-6(10)",
    "CCI-002361": "AC-12",
    "CCI-002363": "AC-12",
    "CCI-002418": "SC-8",
    "CCI-002420": "SC-8(2)",
    "CCI-002421": "SC-8(1)",
    "CCI-002422": "SC-8(2)",
    "CCI-002450": "SC-13",
    "CCI-002696": "SI-6",
    "CCI-002699": "SI-6",
    "CCI-002702": "SI-6",
    "CCI-002884": "MA-4(6)",
    "CCI-002890": "MA-4(6)",
    "CCI-003123": "MA-4(6)",
    "CCI-003627": "AC-6(10)",
}

# Severity mapping
SEVERITY_MAP = {
    "high": "CAT I",
    "medium": "CAT II",
    "low": "CAT III",
}


@dataclass
class STIGRule:
    """Represents a single STIG rule extracted from XCCDF XML."""

    vuln_id: str
    rule_id: str
    stig_id: str
    title: str
    severity: str
    category: str
    weight: float
    description: str
    check_content: str
    fix_content: str
    cci_ids: list = field(default_factory=list)
    nist_controls: list = field(default_factory=list)
    legacy_ids: list = field(default_factory=list)
    srg_id: str = ""
    fix_id: str = ""


def clean_html_description(raw: str) -> str:
    """Extract VulnDiscussion text from HTML-encoded description."""
    decoded = html.unescape(raw)
    match = re.search(
        r"<VulnDiscussion>(.*?)</VulnDiscussion>", decoded, re.DOTALL
    )
    if match:
        return match.group(1).strip()
    return decoded.strip()


def parse_xccdf(xml_path: str) -> list:
    """
    Parse a DISA STIG XCCDF XML file and extract all rules.

    Args:
        xml_path: Path to the XCCDF XML file.

    Returns:
        List of STIGRule objects.
    """
    # Use defusedxml if available to prevent entity expansion DoS attacks
    parser = SafeET if SafeET else ET
    tree = parser.parse(xml_path)
    root = tree.getroot()

    # Detect namespace
    ns_match = re.match(r"\{(.+?)\}", root.tag)
    ns = {"xccdf": ns_match.group(1)} if ns_match else {}

    # XPath prefix
    def xp(tag):
        return f"xccdf:{tag}" if ns else tag

    rules = []

    # Find all Group elements (each contains one Rule)
    for group in root.iter(f"{{{ns['xccdf']}}}Group" if ns else "Group"):
        vuln_id = group.get("id", "")

        # Get SRG title
        srg_title_el = group.find(xp("title"), ns)
        srg_id = srg_title_el.text if srg_title_el is not None else ""

        # Find the Rule within this Group
        rule_el = group.find(xp("Rule"), ns)
        if rule_el is None:
            continue

        rule_id = rule_el.get("id", "")
        severity = rule_el.get("severity", "medium")
        weight = float(rule_el.get("weight", "10.0"))
        category = SEVERITY_MAP.get(severity, "CAT II")

        # STIG ID (version element)
        version_el = rule_el.find(xp("version"), ns)
        stig_id = version_el.text if version_el is not None else ""

        # Title
        title_el = rule_el.find(xp("title"), ns)
        title = title_el.text if title_el is not None else ""

        # Description
        desc_el = rule_el.find(xp("description"), ns)
        description = ""
        if desc_el is not None and desc_el.text:
            description = clean_html_description(desc_el.text)

        # Check content
        check_content = ""
        check_el = rule_el.find(f".//{xp('check-content')}", ns)
        if check_el is not None and check_el.text:
            check_content = check_el.text.strip()

        # Fix content
        fix_content = ""
        fixtext_el = rule_el.find(xp("fixtext"), ns)
        if fixtext_el is not None and fixtext_el.text:
            fix_content = fixtext_el.text.strip()

        fix_id_attr = fixtext_el.get("fixref", "") if fixtext_el is not None else ""

        # CCI identifiers and legacy IDs
        cci_ids = []
        legacy_ids = []
        for ident_el in rule_el.findall(xp("ident"), ns):
            system = ident_el.get("system", "")
            text = ident_el.text or ""
            if "cci" in system:
                cci_ids.append(text)
            elif "legacy" in system:
                legacy_ids.append(text)

        # Map CCIs to NIST 800-53 controls
        nist_controls = list(
            set(
                CCI_TO_NIST[cci]
                for cci in cci_ids
                if cci in CCI_TO_NIST
            )
        )
        nist_controls.sort()

        rules.append(
            STIGRule(
                vuln_id=vuln_id,
                rule_id=rule_id,
                stig_id=stig_id,
                title=title,
                severity=severity,
                category=category,
                weight=weight,
                description=description,
                check_content=check_content,
                fix_content=fix_content,
                cci_ids=cci_ids,
                nist_controls=nist_controls,
                legacy_ids=legacy_ids,
                srg_id=srg_id,
                fix_id=fix_id_attr,
            )
        )

    return rules


def generate_summary(rules: list) -> dict:
    """Generate summary statistics for parsed STIG rules."""
    total = len(rules)
    by_severity = {"CAT I": 0, "CAT II": 0, "CAT III": 0}
    nist_families = {}

    for rule in rules:
        by_severity[rule.category] = by_severity.get(rule.category, 0) + 1
        for ctrl in rule.nist_controls:
            family = ctrl.split("(")[0].split("-")[0] + "-" + ctrl.split("(")[0].split("-")[1] if "-" in ctrl else ctrl
            nist_families[family] = nist_families.get(family, 0) + 1

    return {
        "total_rules": total,
        "by_severity": by_severity,
        "nist_control_families": dict(sorted(nist_families.items())),
        "rules_with_fix_content": sum(1 for r in rules if r.fix_content),
        "rules_with_check_content": sum(1 for r in rules if r.check_content),
    }


def main():
    parser = argparse.ArgumentParser(
        description="Parse DISA STIG XCCDF XML and extract structured rule data."
    )
    parser.add_argument("xccdf_file", help="Path to XCCDF XML file")
    parser.add_argument(
        "--output", "-o", default=None, help="Output JSON file (default: stdout)"
    )
    parser.add_argument(
        "--summary", "-s", action="store_true", help="Print summary statistics"
    )
    args = parser.parse_args()

    if not Path(args.xccdf_file).exists():
        print(f"Error: File not found: {args.xccdf_file}", file=sys.stderr)
        sys.exit(1)

    rules = parse_xccdf(args.xccdf_file)

    if args.summary:
        summary = generate_summary(rules)
        print(json.dumps(summary, indent=2))
        return

    output_data = {
        "metadata": {
            "source_file": str(Path(args.xccdf_file).name),
            "parser_version": "1.0.0",
            "total_rules_parsed": len(rules),
        },
        "summary": generate_summary(rules),
        "rules": [asdict(r) for r in rules],
    }

    if args.output:
        with open(args.output, "w") as f:
            json.dump(output_data, f, indent=2)
        print(f"Wrote {len(rules)} rules to {args.output}", file=sys.stderr)
    else:
        print(json.dumps(output_data, indent=2))


if __name__ == "__main__":
    main()
